/**
 * Research: accrue research points and complete technologies.
 *
 * Spec chapter 7: research points are generated by R&D, universities, grants
 * and research contracts. Here they come from staff, scaled by the university
 * partnership and quantum modifiers, and accrue daily.
 *
 * Completing a technology adds its effects to the modifier stack and its
 * unlocks to the research state. Prerequisites and company level are enforced
 * at start, never at completion, so a started project always finishes.
 */

import type { SimulationTick } from '../../core/clock.js';
import type { ISimulationSystem, SimulationContext } from '../context.js';
import { rebuildModifiers } from '../context.js';

export class ResearchSystem implements ISimulationSystem {
  readonly name = 'research';
  readonly order = 115;

  tick(tick: SimulationTick, context: SimulationContext): void {
    if (!tick.cadence.day) return;
    const state = context.state;
    const company = state.company;

    const annualPoints = company.staffCount * context.balance.researchPointsPerStaffYear
      * context.modifiers.value('research.pointsPerYear', 1);
    company.researchPoints += annualPoints / 365.25;

    if (!state.research.activeId) return;
    const technology = context.registry.technology(state.research.activeId, context.scenario.id);
    const dailyRate = technology.research.durationDays > 0
      ? technology.research.costRP / technology.research.durationDays
      : technology.research.costRP;

    const spend = Math.min(company.researchPoints, dailyRate,
      technology.research.costRP - state.research.activeProgressRP);
    if (spend <= 0) return;

    company.researchPoints -= spend;
    state.research.activeProgressRP += spend;
    if (state.research.activeProgressRP < technology.research.costRP) return;

    state.research.completed.push(technology.id);
    state.research.activeId = null;
    state.research.activeProgressRP = 0;

    for (const id of technology.unlocks.cooling ?? []) {
      if (!state.research.unlockedCooling.includes(id)) state.research.unlockedCooling.push(id);
    }
    for (const id of technology.unlocks.power ?? []) {
      if (!state.research.unlockedPower.includes(id)) state.research.unlockedPower.push(id);
    }
    for (const id of technology.unlocks.hardware ?? []) {
      if (!state.research.unlockedHardware.includes(id)) state.research.unlockedHardware.push(id);
    }
    for (const id of technology.unlocks.contracts ?? []) {
      if (!state.research.unlockedContracts.includes(id)) state.research.unlockedContracts.push(id);
    }
    for (const capability of technology.unlocks.capabilities ?? []) {
      if (!state.research.capabilities.includes(capability)) state.research.capabilities.push(capability);
    }

    rebuildModifiers(context);
    context.diagnostic('research.completed', `Researched ${technology.name}`, {
      tick: tick.index, technologyId: technology.id, tier: technology.tier,
      costRP: technology.research.costRP, tradeOff: technology.tradeOff,
    });
  }
}

/** True when every prerequisite is complete and the company is senior enough. */
export function canStartResearch(context: SimulationContext, technologyId: string): boolean {
  const state = context.state;
  if (state.research.completed.includes(technologyId)) return false;
  const technology = context.registry.all('technologies').get(technologyId);
  if (!technology) return false;
  if (technology.research.minimumCompanyLevel > state.company.companyLevel) return false;
  return technology.prerequisites.every((id) => state.research.completed.includes(id));
}
