/**
 * Builds the browser console bundle.
 *
 * Two steps:
 *   1. Inline every content definition into src/browser/content-data.ts. The
 *      browser cannot read the content tree from disk, and it cannot run ajv,
 *      so schema validation happens HERE - the build refuses to emit content
 *      that does not validate.
 *   2. Bundle the worker with esbuild into web/engine.worker.js.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { build } from 'esbuild';
import { importContent } from '../src/content/importer.ts';
import { validateContent } from '../src/content/validator.ts';

const ROOT = process.cwd();
const CONTENT = join(ROOT, 'content');

// Directory -> registry kind, mirroring the Node importer's own routing.
const DIRECTORIES = [
  ['regions', 'regions'], ['cooling', 'cooling'], ['power', 'power'], ['hardware', 'hardware'],
  ['workloads', 'workloads'], ['contracts', 'contracts'], ['technologies', 'technologies'],
  ['events', 'events'], ['scenarios', 'scenarios'],
];
const PROFILE_PREFIXES = [['score.', 'scoreProfiles'], ['balance.', 'balanceProfiles']];

function collect() {
  const bundle = {};
  for (const [, kind] of [...DIRECTORIES, ...PROFILE_PREFIXES]) bundle[kind] = [];

  for (const [dir, kind] of DIRECTORIES) {
    const path = join(CONTENT, dir);
    if (!existsSync(path)) continue;
    for (const file of readdirSync(path).filter((f) => f.endsWith('.json')).sort()) {
      const full = join(path, file);
      bundle[kind].push({
        file: relative(ROOT, full),
        definition: JSON.parse(readFileSync(full, 'utf8')),
      });
    }
  }

  const profiles = join(CONTENT, 'profiles');
  if (existsSync(profiles)) {
    for (const file of readdirSync(profiles).filter((f) => f.endsWith('.json')).sort()) {
      const route = PROFILE_PREFIXES.find(([prefix]) => file.startsWith(prefix));
      if (!route) continue;
      const full = join(profiles, file);
      bundle[route[1]].push({
        file: relative(ROOT, full),
        definition: JSON.parse(readFileSync(full, 'utf8')),
      });
    }
  }
  return bundle;
}

// Step 1: validate against the schemas, then inline.
const imported = importContent('content');
const report = validateContent(imported.registry, imported);
if (!report.ok) {
  for (const issue of report.errors) {
    console.error(`error  ${issue.file}${issue.field ? ` [${issue.field}]` : ''}: ${issue.message}`);
  }
  console.error(`\n${report.errors.length} content error(s); refusing to build the web bundle.`);
  process.exit(1);
}
for (const issue of report.warnings) {
  console.warn(`warn   ${issue.file}: ${issue.message}`);
}

const bundle = collect();
const total = Object.values(bundle).reduce((sum, list) => sum + list.length, 0);
writeFileSync(
  join(ROOT, 'src/browser/content-data.ts'),
  `/**\n * Generated by scripts/build-web.mjs - do not edit.\n *\n * Every content definition, inlined for the browser build. Regenerate with\n * \`npm run build:web\`; the source of truth is the content/ tree.\n */\n\n/* eslint-disable */\nexport const CONTENT = ${JSON.stringify(bundle)} as const;\n`,
);
console.log(`Inlined ${total} definitions (content hash ${imported.registry.contentHash()})`);

// Step 2: bundle the worker for the browser.
const result = await build({
  entryPoints: ['src/browser/engine-api.ts'],
  outfile: 'web/engine.js',
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  legalComments: 'none',
  metafile: true,
});
const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`Bundled web/engine.js (${(bytes / 1024).toFixed(0)} KB)`);
